[atem]
ip = "10.73.4.40"
video_mode = "1080p25"

[atem.settings.inputs]
input1 = "Laptop"
input3 = "Kamera"
input2 = "VGA"
input4 = "Infobeamer"

[gtk-settings]
gtk-application-prefer-dark-theme = true
gtk-theme-name = "Adwaita"

[logging]
format = "%(name)25s [%(levelname)-8s] %(message)s"
level = "DEBUG"

